// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  about: dynamic(() => import("./About")),
  conferences: dynamic(() => import("./Conferences")),
  hero: dynamic(() => import("./Hero")),
  services: dynamic(() => import("./Services")),
};
